#!/bin/bash
git clone --single-branch -b blog_vfa https://github.com/qMRLab/t1_notebooks.git
cd t1_notebooks
git clone --single-branch -b blog_vfa https://github.com/neuropoly/qMRLab.git
chmod -R 777 $HOME/work/t1_notebooks
octave --eval "cd qMRLab; startup; pkg list;"
